version: '3.3'

x-anchors:
  # Definition of YAML anchors
  python_image: &python_image "davidlor/python-git-app:3.9-buster"  # https://github.com/David-Lor/Docker-Python-Git-App
  git_branch: &git_branch "develop"

services:
  mongo:
    # https://hub.docker.com/_/mongo
    container_name: vigobus_mongodb
    image: mongo
    volumes:
      - mongo:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - backend

  vigobus_api:
    container_name: vigobus_api
    image: *python_image
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - vigobus_api.env
    environment:
      GIT_REPOSITORY: https://github.com/David-Lor/Python_VigoBusAPI.git
      GIT_BRANCH: *git_branch
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - backend

  persistence_api:
    container_name: vigobus_persistenceapi
    image: *python_image
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - persistence_api.env
    environment:
      GIT_REPOSITORY: https://github.com/David-Lor/Telegram-BusBot-DataManager.git
      GIT_BRANCH: *git_branch
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - backend

  vigobus_telegrambotapi:
    # https://github.com/lukaszraczylo/tdlib-telegram-bot-api-docker
    container_name: vigobus_telegrambotapi
    image: ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - telegram_botapi.env
    restart: unless-stopped
    networks:
      - frontend

  vigobus_bot:
    container_name: vigobus_bot
    image: *python_image
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GIT_REPOSITORY: https://github.com/David-Lor/VigoBus-TelegramBot.git
      GIT_BRANCH: *git_branch
      API_URL: http://vigobusapi:5000
      PERSIST_URL: http://vigobus_persistence_api:5000
    env_file:
      - vigobus_bot.env
    secrets:
      - telegram_token
      - telegram_persist_salt
    depends_on:
      - vigobus_telegrambotapi
      - vigobus_api
      - persistence_api
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
    internal: false
  backend:
    driver: bridge
    internal: true

secrets:
  telegram_token:
    file: telegram_token.txt
  telegram_persist_salt:
    file: telegram_persist_salt.txt

volumes:
  mongo: {}
